import Header from "@/components/common/Header/Header";
import { TopNavBar } from "@/components/common/TopNavBar/TopNavBar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function CompanyLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main>
      <TopNavBar />
      <Header />
      {children}
    </main>
  );
}
